Vmd
ngtrgiabaoB2012063/meet-with-us pull request #33
Opened 2023-02-11 09:52 UTC by B2012079VuongMinhDang

@ngtrgiabaoB2012063 : Kiểm tra coi được chưa

2023-02-11 11:20 UTC, ngtrgiabaoB2012063 requested changes
Điều chỉnh lại @B2012079VuongMinhDang @ @

2023-02-11 11:20 UTC, ngtrgiabaoB2012063 commented on backend/app.js
> +const middleWare = require("./src/api/v1/user/user.middleware");
điều chỉnh lại đường dẫn cho gọn

2023-02-11 11:20 UTC, ngtrgiabaoB2012063 commented on backend/server.js
>  app.listen(3000, () => {
Đưa port vào file .env

2023-02-11 11:20 UTC, ngtrgiabaoB2012063 commented on backend/src/api/v1/user/user.middleware.js
> +const userValidation = require("./user.validation");
Khai báo sao không sd?

2023-02-11 11:20 UTC, ngtrgiabaoB2012063 commented on backend/src/api/v1/user/user.middleware.js
> +/* ==================================  ÁP DỤNG STRATEGY PATTERN ===============================================*/
where? Chưa thấy áp dụng

2023-02-11 11:22 UTC, ngtrgiabaoB2012063 requested changes
Điều chinh lại

2023-02-12 11:03 UTC, B2012079VuongMinhDang commented on backend/src/api/v1/user/user.middleware.js
> +/* ==================================  ÁP DỤNG STRATEGY PATTERN ===============================================*/
@ngtrgiabaoB2012063 chia thành nhiều module là strategy rồi đó 🤓

2023-02-12 11:04 UTC, B2012079VuongMinhDang commented on backend/server.js
>  app.listen(3000, () => {
ok

2023-02-13 07:44 UTC, merged